### ISSUE TITLE
border:1px solid #eee; 不转换

### ISSUE THREAD

**Issue by pbwei** [songsiqi/px2rem-postcss#10]
border:1px solid #eee;
这种 格式 转化为 rem 了 
可以有配置 不转换么

**Comment by Sapphire2k** [comment]
通过行内注释 /*no*/  
但是 webpack build 的时候 会去掉注释。。。

**Comment by pbwei** [comment]
OK

**Comment by brucekong** [comment]
border:1px solide #f00 /*no*/；
是用这种格式，写在同一行
