### ISSUE TITLE
怎么忽略1px的问题

### ISSUE THREAD

**Issue by lanmei** [songsiqi/px2rem-postcss#13]
请问不想让1px边框被转为rem，怎么配置？？

**Comment by songsiqi** [comment]
用 `/*no*/`

**Comment by taomas** [comment]
我用的`postcss-px2rem`加`precss`，好像用`/*no*/`还是无效，请问你们解决了么

**Comment by chuchur** [comment]
的确是的1px 用/*no*/ 或者 /*px*/ 是无效的

**Comment by babaysite** [comment]
不能写个igonre 配置参数来做全局忽略么

**Comment by chuchur** [comment]
别回了. 用 postcss-pxtorem 吧.  options  => minPixelValue:2   小于2像素的不转换.
