### ISSUE TITLE
配合 webpack UglifyJsPlugin  ，ExtractTextPlugin  一起使用, 注释失效

### ISSUE THREAD

**Issue by sandwich99** [songsiqi/px2rem-postcss#4]
压缩后， 注释 /*no*/ /*px*/ 失效。
经测试， 单独使用 UglifyJsPlugin 也会出现该问题。

 不明原因， 推测是 loader 和 plugin 加载的时序有问题

但是暂时还没有找到方法控制时序

**Comment by songsiqi** [comment]
这个issue已经提过了 https://github.com/songsiqi/px2rem/issues/2
