### ISSUE TITLE
1px 2px 转 rem后，有些安卓机就不显示

### ISSUE THREAD

**Issue by imcss4html** [songsiqi/px2rem-postcss#9]
1px 2px 转 rem后，有些安卓机就不显示，
可否支持一下参数配置，对1px 2px不进行转换

**Comment by songsiqi** [comment]
可以加 `/*no*/` 参数，标记不显示。

缩放 viewport 的方案现在看来已经有些落伍了，后面更推荐使用这个：[postcss-adaptive](https://www.npmjs.com/package/postcss-adaptive)
